#! /bin/bash
docker build -t casparcg/server-build:ubuntu-16.04 $PWD/build-scripts/ubuntu-16.04

docker run --rm -it \
    -v $PWD:/source \
    -v $PWD/products:/build/products \
    casparcg/server-build:ubuntu-16.04 /bin/bash -c "cmake /source && make -j2 && /source/build-scripts/ubuntu-16.04/package"
